version: '3'

volumes:
  pg_data:
services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_1}
      POSTGRES_DB: ${POSTGRES_DB_1}
    container_name: database
  bot:
    build:
      context: .
    volumes:
      - .:/app
    command: bash -c "alembic upgrade head && python bot/bot.py"
    restart: always
    env_file: .env
    depends_on:
      - db