"""add updated_at column to sellers

Revision ID: 65d8089c67d9
Revises: de70999b761d
Create Date: 2024-01-31 22:53:21.570621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65d8089c67d9"
down_revision: Union[str, None] = "de70999b761d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sellers", sa.Column("updated_at", sa.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sellers", "updated_at")
    # ### end Alembic commands ###
