"""Create stocks table

Revision ID: be82fe2cce83
Revises: 0b48e9cdcb54
Create Date: 2024-01-25 19:02:13.797571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be82fe2cce83"
down_revision: Union[str, None] = "0b48e9cdcb54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("seller_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("last_change_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("warehouse_name", sa.String(), nullable=True),
        sa.Column("supplier_article", sa.String(), nullable=True),
        sa.Column("barcode", sa.String(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("in_way_to_client", sa.Integer(), nullable=True),
        sa.Column("in_way_from_client", sa.Integer(), nullable=True),
        sa.Column("quantity_full", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("brand", sa.String(), nullable=True),
        sa.Column("tech_size", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("discount", sa.Float(), nullable=True),
        sa.Column("is_supply", sa.Boolean(), nullable=True),
        sa.Column("is_realization", sa.Boolean(), nullable=True),
        sa.Column("sc_code", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "seller_id",
            "last_change_date",
            "warehouse_name",
            "product_id",
            name="seller_product_warehouse_change_date_key",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stocks")
    # ### end Alembic commands ###
