"""Create products table

Revision ID: 0b48e9cdcb54
Revises: 5486dfd1cb86
Create Date: 2024-01-25 19:00:35.982821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b48e9cdcb54"
down_revision: Union[str, None] = "5486dfd1cb86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("seller_id", sa.Integer(), nullable=False),
        sa.Column("nm_id", sa.Integer(), nullable=True),
        sa.Column("imt_id", sa.Integer(), nullable=True),
        sa.Column("nm_uuid", sa.String(), nullable=True),
        sa.Column("subject_id", sa.Integer(), nullable=True),
        sa.Column("subject_name", sa.String(), nullable=True),
        sa.Column("vendor_code", sa.String(), nullable=True),
        sa.Column("brand", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("video", sa.String(), nullable=True),
        sa.Column("photos", sa.JSON(), nullable=True),
        sa.Column("length", sa.Float(), nullable=True),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("characteristics", sa.JSON(), nullable=True),
        sa.Column("sizes", sa.JSON(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seller_id", "nm_id", name="seller_nm_id_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###
